org.gradle.jvmargs=-Xmx6G -XX:MaxMetaspaceSize=2G -Dfile.encoding=UTF-8
android.useAndroidX=true
android.enableJetifier=true

# FORCE Gradle to use Android Studio JBR (Java 17+)
org.gradle.java.home=C:\\Program Files\\Android\\Android Studio\\jbr
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
